---
# tasks file for pxe-dhcp
incule_vars: defaults/main.yml

- name: Update server
  apt: name=* state=latest

- name: Install dependencies for PXE Server
  apt: name={ item } state=present
  with_items:
        - isc-dhcp-server

- name: Send dhcpd config file
  copy: src=files/dhcpd.conf dest=/etc/dhcp/dhcpd.conf mode=0644